version: '3'
services:
  nft-rent-marketplace-api:
    container_name: mktplace-api
    build: 
      context: ./api
      dockerfile: DockerfileDev
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env

  nft-rent-marketplace-worker:
    container_name: mktplace-worker
    build: 
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    links:
      - nft-rent-marketplace-api
    env_file:
      - .env

  nft-rent-marketplace-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - nft-rent-marketplace-api
    env_file:
      - .env
