service: nft-rent-marketplace-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  memorySize: 128
  timeout: 10
  environment:
    WALLET_PV_KEY: ${env:WALLET_PV_KEY}
    BLOCKCHAIN_RPC_URL: ${env:BLOCKCHAIN_RPC_URL}
    NFT_RENT_MARKETPLACE_CONTRACT: ${env:NFT_RENT_MARKETPLACE_CONTRACT}
    NFT_RENT_MARKETPLACE_API: ${env:NFT_RENT_MARKETPLACE_API}

functions:
  app:
    handler: api/server.handler
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: any
