name: CI/CD Pipeline for API

on:
  push:
    branches: [ main ]
    paths:
    - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd api
        npm ci

    - name: Deploy API
      run: |
        npx serverless-deploy
